version: '2'

services:
  lde.web:
    image: lde.web
    volumes:
      - /bin/nano:/bin/nano
    ports:
      - 80:80
    #build:
    #  context: ./
    #dockerfile: Dockerfile
    depends_on: 
     - "mongodb"
    restart: always
  
  mongodb:
    image: mongo
    volumes:
      - /var/mongo:/data/db
    #ports:
    #  - 27017:27017
    restart: always
